### ISSUE TITLE
Random image dimensions on car listing

### ISSUE THREAD

**Issue by birat54** [Sa400554/vroom-collab#3]
The image for the car listing is random everytime on the car listing

**Comment by Aey-Sama** [comment]
> The image for the car listing is random everytime on the car listing

assigne a unique id to the isting lik i have done for adding car it generates random id every time

**Comment by birat54** [comment]
no i mean the dimensions are wrong

**Comment by Aey-Sama** [comment]
> no i mean the dimensions are wrong

make it cover no repeat on css 
or contain

**Comment by birat54** [comment]
check my code on google chat

**Comment by Sa400554** [comment]
> check my code on google chat

Checked

**Comment by nischal12aryal** [comment]
ok i wll check that
